const IS_LOCAL=['localhost','127.0.0.1'].includes(location.hostname);
const API_URL=IS_LOCAL?'http://localhost:5001/api':'https://hovalot-production.up.railway.app/api';
const token=localStorage.getItem('token')||sessionStorage.getItem('token');
if(!token)location.href='admin.html';
const $=id=>document.getElementById(id);
let services=[],appointments=[],galleryImages=[],installPrompt=null;

async function api(path,options={}){
  options.headers={...(options.headers||{}),Authorization:`Bearer ${token}`};
  const response=await fetch(API_URL+path,options),data=await response.json().catch(()=>({}));
  if(response.status===401){localStorage.removeItem('token');sessionStorage.removeItem('token');location.href='admin.html'}
  if(!response.ok)throw new Error(data.error||'הפעולה נכשלה');
  return data;
}
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const dateKey=value=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date(value));
const displayDate=value=>new Date(value).toLocaleDateString('he-IL',{timeZone:'Asia/Jerusalem'});
const normalizePhone=value=>String(value||'').replace(/\D/g,'').replace(/^972/,'0');
const whatsappPhone=value=>{const digits=String(value||'').replace(/\D/g,'');return digits.startsWith('0')?`972${digits.slice(1)}`:digits};
const statusLabel=status=>({confirmed:'מאושר',pending:'ממתין',cancelled:'מבוטל',completed:'הושלם','no-show':'לא בוצע'})[status]||status;

function reminderText(appointment){return `🚚 שלום ${appointment.customerName},\n⏰ תזכורת להובלה שנקבעה לתאריך ${displayDate(appointment.date)} בשעה ${appointment.time}.\n📍 איסוף: ${appointment.pickupAddress}\n🏁 יעד: ${appointment.destinationAddress}\nתודה, הובלות חיפה והקריות 🙏`}
function confirmationText(appointment){return `🚚 שלום ${appointment.customerName}, ההובלה שלך נקבעה בהצלחה!\n📅 תאריך: ${displayDate(appointment.date)}\n🕐 שעה: ${appointment.time}\n📍 איסוף: ${appointment.pickupAddress}\n🏁 יעד: ${appointment.destinationAddress}\nתודה שבחרת בהובלות חיפה והקריות 🙏`}
function changesText(before,after){const changes=[];if(before.customerName!==after.customerName)changes.push(`👤 שם: ${after.customerName}`);if(before.customerPhone!==after.customerPhone)changes.push(`📱 טלפון: ${after.customerPhone}`);if(before.pickupAddress!==after.pickupAddress)changes.push(`📍 איסוף: ${after.pickupAddress}`);if(before.destinationAddress!==after.destinationAddress)changes.push(`🏁 יעד: ${after.destinationAddress}`);if(before.service!==after.service)changes.push(`📦 סוג הובלה: ${after.service}`);if(dateKey(before.date)!==dateKey(after.date))changes.push(`📅 תאריך: ${displayDate(after.date)}`);if(before.time!==after.time)changes.push(`🕐 שעה: ${after.time}`);if(before.status!==after.status)changes.push(`✅ סטטוס: ${statusLabel(after.status)}`);return `🚚 שלום ${after.customerName},\nבוצעו שינויים בפרטי ההובלה שלך:\n${changes.length?changes.join('\n'):'פרטי ההובלה עודכנו.'}\nתודה, הובלות חיפה והקריות 🙏`}
function whatsappUrl(appointment,text=reminderText(appointment)){return `https://wa.me/${whatsappPhone(appointment.customerPhone)}?text=${encodeURIComponent(text)}`}

async function loadServices(){services=await api('/services');const options='<option value="">בחר שירות</option>'+services.map(item=>`<option value="${escapeHtml(item.name)}">${escapeHtml(item.name)}</option>`).join('');$('service').innerHTML=options;$('editService').innerHTML=options}
async function loadRole(){const data=await api('/admin/me');if(data.role==='superadmin')$('superAdminNotificationSection').classList.remove('hidden')}
async function loadAppointments(){const data=await api('/appointments');appointments=data.data||[];renderAppointments()}
function renderAppointments(){const filter=$('dateFilter').value,list=filter?appointments.filter(item=>dateKey(item.date)===filter):appointments;list.sort((a,b)=>dateKey(a.date).localeCompare(dateKey(b.date))||String(a.time).localeCompare(String(b.time)));$('movingCount').textContent=`${list.length} הובלות`;$('movingsList').innerHTML=list.length?list.map(item=>`<article class="moving-card"><div class="moving-date"><strong>${escapeHtml(item.time)}</strong><span>${displayDate(item.date)}</span></div><div class="moving-main"><strong>${escapeHtml(item.customerName)}</strong><p>${escapeHtml(item.customerPhone)} · ${escapeHtml(item.service)}</p><span class="status">${statusLabel(item.status)}</span></div><div class="moving-route"><p><b>מאיסוף:</b> ${escapeHtml(item.pickupAddress)}</p><p><b>ליעד:</b> ${escapeHtml(item.destinationAddress)}</p></div><div class="moving-actions"><a class="whatsapp" href="${whatsappUrl(item)}" target="_blank" rel="noopener">WhatsApp</a><button onclick="openEdit('${item._id}')">עריכה</button><button class="danger" onclick="deleteMoving('${item._id}')">מחיקה</button></div></article>`).join(''):'<p>אין הובלות להצגה.</p>'}

async function createMoving(event){event.preventDefault();const payload={customerName:$('customerName').value.trim(),customerPhone:normalizePhone($('customerPhone').value),pickupAddress:$('pickupAddress').value.trim(),destinationAddress:$('destinationAddress').value.trim(),service:$('service').value,date:$('movingDate').value,time:$('movingTime').value};try{const result=await api('/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),created=result.data||payload;$('movingMessage').textContent='ההובלה נוספה בהצלחה';$('movingMessage').className='form-message success';event.target.reset();const today=dateKey(new Date());$('movingDate').min=today;$('movingDate').value=today;await loadAppointments();if(confirm('ההובלה נוספה. האם לשלוח ללקוח הודעת אישור ב־WhatsApp?'))location.href=whatsappUrl(created,confirmationText(created))}catch(error){$('movingMessage').textContent=error.message;$('movingMessage').className='form-message error'}}

function openEdit(id){const item=appointments.find(a=>a._id===id);if(!item)return;$('editId').value=id;$('editName').value=item.customerName;$('editPhone').value=item.customerPhone;$('editPickup').value=item.pickupAddress;$('editDestination').value=item.destinationAddress;$('editService').value=item.service;$('editDuration').value=item.duration||30;$('editDate').value=dateKey(item.date);$('editTime').value=item.time;$('editStatus').value=item.status;$('editNotes').value=item.notes||'';$('editMessage').textContent='';$('messagesPanel').classList.add('hidden');$('editModal').classList.remove('hidden')}
async function saveEdit(event){event.preventDefault();const id=$('editId').value,before=appointments.find(item=>item._id===id),payload={customerName:$('editName').value.trim(),customerPhone:normalizePhone($('editPhone').value),pickupAddress:$('editPickup').value.trim(),destinationAddress:$('editDestination').value.trim(),service:$('editService').value,duration:Number($('editDuration').value),date:$('editDate').value,time:$('editTime').value,status:$('editStatus').value,notes:$('editNotes').value.trim()};try{const result=await api('/appointments/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),updated=result.data||{...before,...payload};$('editMessage').textContent='השינויים נשמרו';$('editMessage').className='form-message success';await loadAppointments();$('editModal').classList.add('hidden');if(confirm('השינויים נשמרו. האם לשלוח ללקוח הודעה עם הפרטים שעודכנו?'))location.href=whatsappUrl(updated,changesText(before,updated))}catch(error){$('editMessage').textContent=error.message;$('editMessage').className='form-message error'}}
async function deleteMoving(id){if(!confirm('למחוק את ההובלה?'))return;try{await api('/appointments/'+id,{method:'DELETE'});await loadAppointments()}catch(error){alert(error.message)}}

async function loadMessages(){try{const data=await api('/messages');$('messagesBadge').textContent=data.unreadCount>99?'99+':String(data.unreadCount);$('messagesBadge').classList.toggle('hidden',!data.unreadCount);$('messagesList').innerHTML=data.data.length?data.data.map(message=>{const appointment=appointments.find(item=>item._id===String(message.appointment));return`<article class="notification-card ${message.readAt?'':'unread'}"><h3>${escapeHtml(message.title)}</h3><time>${new Date(message.createdAt).toLocaleString('he-IL',{timeZone:'Asia/Jerusalem'})}</time><p>${escapeHtml(message.body)}</p><div class="notification-actions">${appointment?`<a class="whatsapp" href="${whatsappUrl(appointment)}" target="_blank" rel="noopener">שליחת תזכורת ב־WhatsApp</a><button onclick="openEdit('${appointment._id}')">עריכה</button>`:''}<button class="danger" onclick="deleteMessage('${message._id}')">מחיקת הודעה</button></div></article>`}).join(''):'<p>אין הודעות.</p>'}catch(error){console.error(error)}}
async function openMessages(){await Promise.all([loadAppointments(),loadMessages()]);$('messagesPanel').classList.remove('hidden');await api('/messages/read-all',{method:'PUT'});$('messagesBadge').classList.add('hidden');$('messagesList').querySelectorAll('.unread').forEach(item=>item.classList.remove('unread'))}
async function deleteMessage(id){if(!confirm('למחוק את ההודעה?'))return;await api('/messages/'+id,{method:'DELETE'});await loadMessages()}

async function loadGallery(){try{galleryImages=await api('/gallery');renderGallery()}catch(error){showGallery(error.message,'error')}}
function renderGallery(){$('galleryContainer').innerHTML=galleryImages.map((image,index)=>`<article class="gallery-item"><img src="${image.image}" alt="תמונת גלריה ${index+1}"><div class="gallery-actions"><button ${index===0?'disabled':''} onclick="moveImage('${image._id}',-1)">↑</button><button ${index===galleryImages.length-1?'disabled':''} onclick="moveImage('${image._id}',1)">↓</button></div><button class="danger" onclick="deleteImage('${image._id}')">מחיקה</button></article>`).join('')}
function moveImage(id,direction){const from=galleryImages.findIndex(item=>item._id===id),to=from+direction;if(from<0||to<0||to>=galleryImages.length)return;[galleryImages[from],galleryImages[to]]=[galleryImages[to],galleryImages[from]];renderGallery()}
async function uploadImage(){const file=$('imageInput').files[0];if(!file)return showGallery('בחר תמונה','error');const form=new FormData();form.append('image',file);try{await api('/gallery',{method:'POST',body:form});$('imageInput').value='';showGallery('התמונה הועלתה','success');await loadGallery()}catch(error){showGallery(error.message,'error')}}
async function saveGalleryOrder(){try{await api('/gallery/order',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageIds:galleryImages.map(item=>item._id)})});showGallery('סדר התמונות נשמר','success')}catch(error){showGallery(error.message,'error')}}
async function deleteImage(id){if(!confirm('למחוק את התמונה?'))return;await api('/gallery/'+id,{method:'DELETE'});await loadGallery()}
function showGallery(text,type){$('galleryMessage').textContent=text;$('galleryMessage').className=`form-message ${type}`}

function b64(value){const padding='='.repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}
async function syncPush(create=false){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('המכשיר אינו תומך בהתראות');if(create&&Notification.permission!=='granted'){const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('יש לאפשר התראות בהגדרות המכשיר')}if(Notification.permission!=='granted')return;const registration=await navigator.serviceWorker.ready,{publicKey}=await api('/push/public-key');let subscription=await registration.pushManager.getSubscription();if(!subscription&&create)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(publicKey)});if(subscription){await api('/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription})});$('enableNotifications').textContent='✅ התראות פעילות'}}
async function enableNotifications(){try{if(!matchMedia('(display-mode: standalone)').matches&&!navigator.standalone)throw new Error('יש להתקין ולפתוח את האפליקציה ממסך הבית לפני הפעלת ההתראות');await syncPush(true)}catch(error){alert(error.message)}}
async function logout(){try{const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription)await api('/push/subscribe',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:subscription.endpoint})})}catch{}localStorage.removeItem('token');sessionStorage.removeItem('token');location.href='admin.html'}

async function refreshDashboard(){const button=$('floatingRefreshButton');button.classList.add('refreshing');button.disabled=true;try{await Promise.all([loadAppointments(),loadMessages(),loadGallery()])}catch(error){alert(error.message)}finally{button.classList.remove('refreshing');button.disabled=false}}
function setupCollapsibleSections(){document.querySelectorAll('.collapse-button').forEach(button=>{const section=$(button.dataset.section),key=`collapsed-${section.id}`,setState=collapsed=>{section.classList.toggle('collapsed',collapsed);button.textContent=collapsed?'+ הגדל':'− הקטן';button.setAttribute('aria-expanded',String(!collapsed))};setState(localStorage.getItem(key)==='1');button.onclick=()=>{const collapsed=!section.classList.contains('collapsed');setState(collapsed);localStorage.setItem(key,collapsed?'1':'0')}})}
async function sendOwnerNotification(event){event.preventDefault();const message=$('ownerNotificationMessage');try{const result=await api('/push/owner-notification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('ownerNotificationTitle').value.trim(),body:$('ownerNotificationBody').value.trim()})});message.textContent=result.sent?`ההתראה נשלחה בהצלחה ל־${result.sent} מכשירים`:'ההודעה נשמרה בלוח ההודעות, אך לבעל העסק אין כרגע מכשיר רשום להתראות';message.className='form-message success';event.target.reset()}catch(error){message.textContent=error.message;message.className='form-message error'}}

window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('installButton').classList.remove('hidden')});
async function installApp(){if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('installBanner').classList.add('hidden')}

document.addEventListener('DOMContentLoaded',async()=>{
  if('serviceWorker'in navigator)await navigator.serviceWorker.register('./moving-sw.js');
  const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  if(!standalone){$('installBanner').classList.remove('hidden');if(/iphone|ipad|ipod/i.test(navigator.userAgent))$('iosInstall').classList.remove('hidden')}
  const today=dateKey(new Date());$('dateFilter').value=today;$('movingDate').min=today;$('movingDate').value=today;$('movingForm').onsubmit=createMoving;$('editForm').onsubmit=saveEdit;$('ownerNotificationForm').onsubmit=sendOwnerNotification;$('dateFilter').onchange=renderAppointments;$('showAllButton').onclick=()=>{$('dateFilter').value='';renderAppointments()};$('refreshButton').onclick=refreshDashboard;$('floatingRefreshButton').onclick=refreshDashboard;$('messagesButton').onclick=openMessages;$('closeMessages').onclick=()=>$('messagesPanel').classList.add('hidden');$('messagesPanel').onclick=event=>{if(event.target===$('messagesPanel'))$('messagesPanel').classList.add('hidden')};$('closeEdit').onclick=()=>$('editModal').classList.add('hidden');$('editModal').onclick=event=>{if(event.target===$('editModal'))$('editModal').classList.add('hidden')};$('enableNotifications').onclick=enableNotifications;$('logoutButton').onclick=logout;$('installButton').onclick=installApp;$('uploadImageButton').onclick=uploadImage;$('saveGalleryOrderButton').onclick=saveGalleryOrder;setupCollapsibleSections();
  try{await loadRole();await loadServices();await Promise.all([loadAppointments(),loadGallery()]);await loadMessages();await syncPush(false)}catch(error){alert(error.message)}
  navigator.serviceWorker?.addEventListener('message',event=>{if(event.data?.type==='moving-message')Promise.all([loadAppointments(),loadMessages()])});
});
